#pragma once

#include "problemsize.h"
#include "mod_debug.h"
#include "mod_mp_nsw6.h"

using namespace PROBLEM_SIZE;
using namespace DEBUG;
using namespace MP_NSW6;

namespace MP_DRIVER{

void mp_init(const std::string& MP_TYPE_in);

void mp_driver( int l_region,
				double rhog          [kdim][ijdim],
				double rhogvx        [kdim][ijdim],
				double rhogvy        [kdim][ijdim],
				double rhogvz        [kdim][ijdim],
				double rhogw         [kdim][ijdim],
				double rhoge         [kdim][ijdim],
				double rhogq         [nqmax][kdim][ijdim],
				double vx            [kdim][ijdim],
				double vy            [kdim][ijdim],
				double vz            [kdim][ijdim],
				double w             [kdim][ijdim],
				double unccn         [kdim][ijdim],
				double rho           [kdim][ijdim],
				double tem           [kdim][ijdim],
				double pre           [kdim][ijdim],
				double q             [nqmax][kdim][ijdim],
				double qd            [kdim][ijdim],
				double precip        [2][ijdim],
				double ISO1_precip   [2][ijdim],
				double ISO2_precip   [2][ijdim],
				double precip_rhoe   [ijdim],
				double precip_lh_heat[ijdim],
				double precip_rhophi [ijdim],
				double precip_rhokin [ijdim],
				double re_liquid	 [kdim][ijdim],
				double re_solid		 [kdim][ijdim],
				double re_cld		 [kdim][ijdim],
				double rctop 		 [1][ijdim],
				double rwtop 		 [1][ijdim],
				double tctop 		 [1][ijdim],
				double frhoge_af     [kdim][ijdim],
				double frhogqv_af    [kdim][ijdim],
				double frhoge_rad    [kdim][ijdim],
				double rhogqke       [kdim][ijdim],
				double gsgam2        [kdim][ijdim],
				double gsgam2h       [kdim][ijdim],
				double gam2          [kdim][ijdim],
				double gam2h         [kdim][ijdim],
				double ix			 [ijdim],
				double iy			 [ijdim],
				double iz			 [ijdim],
				double jx			 [ijdim],
				double jy			 [ijdim],
				double jz			 [ijdim],
				double z			 [kdim][ijdim],
				double zh			 [kdim][ijdim],
				double dt,
				double ct,
				double GDCLW		 [kdim][ijdim],
				double GDCFRC		 [kdim][ijdim],
				double GPREC		 [kdim][ijdim],
				double CBMFX		 [kdim][ijdim]
				);

// Kokkos ver.
void mp_driver( int l_region,
				const View<double**>&  rhog          ,
				const View<double**>&  rhogvx        ,
				const View<double**>&  rhogvy        ,
				const View<double**>&  rhogvz        ,
				const View<double**>&  rhogw         ,
				const View<double**>&  rhoge         ,
				const View<double***>& rhogq         ,
				const View<double**>&  vx            ,
				const View<double**>&  vy            ,
				const View<double**>&  vz            ,
				const View<double**>&  w             ,
				const View<double**>&  unccn         ,
				const View<double**>&  rho           ,
				const View<double**>&  tem           ,
				const View<double**>&  pre           ,
				const View<double***>& q             ,
				const View<double**>&  qd            ,
				const View<double**>&  precip        ,
				const View<double**>&  ISO1_precip   ,
				const View<double**>&  ISO2_precip   ,
				const View<double*>&   precip_rhoe   ,
				const View<double*>&   precip_lh_heat,
				const View<double*>&   precip_rhophi ,
				const View<double*>&   precip_rhokin ,
				const View<double**>&  re_liquid	 ,
				const View<double**>&  re_solid		 ,
				const View<double**>&  re_cld		 ,
				const View<double**>&  rctop 		 ,
				const View<double**>&  rwtop 		 ,
				const View<double**>&  tctop 		 ,
				const View<double**>&  frhoge_af     ,
				const View<double**>&  frhogqv_af    ,
				const View<double**>&  frhoge_rad    ,
				const View<double**>&  rhogqke       ,
				const View<double**>&  gsgam2        ,
				const View<double**>&  gsgam2h       ,
				const View<double**>&  gam2          ,
				const View<double**>&  gam2h         ,
				const View<double*>&   ix			 ,
				const View<double*>&   iy			 ,
				const View<double*>&   iz			 ,
				const View<double*>&   jx			 ,
				const View<double*>&   jy			 ,
				const View<double*>&   jz			 ,
				const View<double**>&  z			 ,
				const View<double**>&  zh			 ,
				double 				   dt			 ,
				double 				   ct			 ,
				const View<double**>&  GDCLW		 ,
				const View<double**>&  GDCFRC		 ,
				const View<double**>&  GPREC		 ,
				const View<double**>&  CBMFX		 
				);
}
