#pragma once

#include "problemsize.h"
#include "mod_debug.h"
#include "mod_mp_nsw6.h"

using namespace PROBLEM_SIZE;
using namespace DEBUG;
using namespace MP_NSW6;

namespace MP_DRIVER{

void mp_init(const std::string& MP_TYPE_in);

void mp_driver( int l_region,
				double rhog          [kdim][ijdim],
				double rhogvx        [kdim][ijdim],
				double rhogvy        [kdim][ijdim],
				double rhogvz        [kdim][ijdim],
				double rhogw         [kdim][ijdim],
				double rhoge         [kdim][ijdim],
				double rhogq         [nqmax][kdim][ijdim],
				double vx            [kdim][ijdim],
				double vy            [kdim][ijdim],
				double vz            [kdim][ijdim],
				double w             [kdim][ijdim],
				double unccn         [kdim][ijdim],
				double rho           [kdim][ijdim],
				double tem           [kdim][ijdim],
				double pre           [kdim][ijdim],
				double q             [nqmax][kdim][ijdim],
				double qd            [kdim][ijdim],
				double precip        [2][ijdim],
				double ISO1_precip   [2][ijdim],
				double ISO2_precip   [2][ijdim],
				double precip_rhoe   [ijdim],
				double precip_lh_heat[ijdim],
				double precip_rhophi [ijdim],
				double precip_rhokin [ijdim],
				double re_liquid	 [kdim][ijdim],
				double re_solid		 [kdim][ijdim],
				double re_cld		 [kdim][ijdim],
				double rctop 		 [1][ijdim],
				double rwtop 		 [1][ijdim],
				double tctop 		 [1][ijdim],
				double frhoge_af     [kdim][ijdim],
				double frhogqv_af    [kdim][ijdim],
				double frhoge_rad    [kdim][ijdim],
				double rhogqke       [kdim][ijdim],
				double gsgam2        [kdim][ijdim],
				double gsgam2h       [kdim][ijdim],
				double gam2          [kdim][ijdim],
				double gam2h         [kdim][ijdim],
				double ix			 [ijdim],
				double iy			 [ijdim],
				double iz			 [ijdim],
				double jx			 [ijdim],
				double jy			 [ijdim],
				double jz			 [ijdim],
				double z			 [kdim][ijdim],
				double zh			 [kdim][ijdim],
				double dt,
				double ct,
				double GDCLW		 [kdim][ijdim],
				double GDCFRC		 [kdim][ijdim],
				double GPREC		 [kdim][ijdim],
				double CBMFX		 [kdim][ijdim]
				);

// Kokkos ver.
void mp_driver( int l_region,
				const View2D<double, DEFAULT_MEM>&  rhog          ,
				const View2D<double, DEFAULT_MEM>&  rhogvx        ,
				const View2D<double, DEFAULT_MEM>&  rhogvy        ,
				const View2D<double, DEFAULT_MEM>&  rhogvz        ,
				const View2D<double, DEFAULT_MEM>&  rhogw         ,
				const View2D<double, DEFAULT_MEM>&  rhoge         ,
				const View3D<double, DEFAULT_MEM>&  rhogq         ,
				const View2D<double, DEFAULT_MEM>&  vx            ,
				const View2D<double, DEFAULT_MEM>&  vy            ,
				const View2D<double, DEFAULT_MEM>&  vz            ,
				const View2D<double, DEFAULT_MEM>&  w             ,
				const View2D<double, DEFAULT_MEM>&  unccn         ,
				const View2D<double, DEFAULT_MEM>&  rho           ,
				const View2D<double, DEFAULT_MEM>&  tem           ,
				const View2D<double, DEFAULT_MEM>&  pre           ,
				const View3D<double, DEFAULT_MEM>&  q             ,
				const View2D<double, DEFAULT_MEM>&  qd            ,
				const View2D<double, DEFAULT_MEM>&  precip        ,
				const View2D<double, DEFAULT_MEM>&  ISO1_precip   ,
				const View2D<double, DEFAULT_MEM>&  ISO2_precip   ,
				const View1D<double, DEFAULT_MEM>&  precip_rhoe   ,
				const View1D<double, DEFAULT_MEM>&  precip_lh_heat,
				const View1D<double, DEFAULT_MEM>&  precip_rhophi ,
				const View1D<double, DEFAULT_MEM>&  precip_rhokin ,
				const View2D<double, DEFAULT_MEM>&  re_liquid	 ,
				const View2D<double, DEFAULT_MEM>&  re_solid		 ,
				const View2D<double, DEFAULT_MEM>&  re_cld		 ,
				const View2D<double, DEFAULT_MEM>&  rctop 		 ,
				const View2D<double, DEFAULT_MEM>&  rwtop 		 ,
				const View2D<double, DEFAULT_MEM>&  tctop 		 ,
				const View2D<double, DEFAULT_MEM>&  frhoge_af     ,
				const View2D<double, DEFAULT_MEM>&  frhogqv_af    ,
				const View2D<double, DEFAULT_MEM>&  frhoge_rad    ,
				const View2D<double, DEFAULT_MEM>&  rhogqke       ,
				const View2D<double, DEFAULT_MEM>&  gsgam2        ,
				const View2D<double, DEFAULT_MEM>&  gsgam2h       ,
				const View2D<double, DEFAULT_MEM>&  gam2          ,
				const View2D<double, DEFAULT_MEM>&  gam2h         ,
				const View1D<double, DEFAULT_MEM>&  ix			 ,
				const View1D<double, DEFAULT_MEM>&  iy			 ,
				const View1D<double, DEFAULT_MEM>&  iz			 ,
				const View1D<double, DEFAULT_MEM>&  jx			 ,
				const View1D<double, DEFAULT_MEM>&  jy			 ,
				const View1D<double, DEFAULT_MEM>&  jz			 ,
				const View2D<double, DEFAULT_MEM>&  z			 ,
				const View2D<double, DEFAULT_MEM>&  zh			 ,
				double 				                dt			 ,
				double 				                ct			 ,
				const View2D<double, DEFAULT_MEM>&  GDCLW		 ,
				const View2D<double, DEFAULT_MEM>&  GDCFRC		 ,
				const View2D<double, DEFAULT_MEM>&  GPREC		 ,
				const View2D<double, DEFAULT_MEM>&  CBMFX		 
				);
}
